spring:
  application:
    name: sysgateway
  cloud:
    gateway:
      globalcors:
        cors‐configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
            - GET
            - POST
            - PUT
            - DELETE
      routes:
        - id: goods  #随便取  对应微服务名称
          uri: lb://goods   #@LoadBalanced  +  /优瑞卡注册的服务名称
          predicates:
            - Path=/goods/**   # 需要进行路由的请求
          filters:
            - StripPrefix= 1    # 过滤掉一个前缀路径
            #  localhost:9101/goods/brand/findAll;
            #路由到   lb://localhost:9001/brand/findAll
            - name: RequestRateLimiter #请求数限流 名字不能随便写
              args:
                key-resolver: "#{@ipKeyResolver}"  # 令牌解析器 ？
                redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 1 #令牌桶总容量
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix= 1
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix= 1
  redis:
    host: 192.168.200.128
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true