server:
  port: 9200
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.200.128
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/changgou_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou  #客户端id
  clientSecret: changgou  #客户端秘钥
  cookieDomain: localhost  #Cookie保存对应的域名
  cookieMaxAge: -1          #Cookie过期时间,-1表示浏览器关闭则销毁
encrypt:
  key-store:
    location: classpath:/changgou.jks
    secret: changgou
    alias: changgou
    password: changgou